### ISSUE TITLE
启动不起来，怎么能看到页面

### ISSUE THREAD

**Issue by wendy88801** [feihua/go-zero-admin-ui#4]

**Comment by wendy88801** [comment]
![image](https://user-images.githubusercontent.com/12087709/156158046-577aeef4-f270-480b-bc3d-bf384b40e333.png)

**Comment by chree188** [comment]
/config/routes.ts  大小写敏感 改一下就行了### component: './user/Login',

**Comment by feihua** [comment]
已修复
