### ISSUE TITLE
npm run dev 报整个错，请问该怎么解决

### ISSUE THREAD

**Issue by 780662833** [feihua/go-zero-admin-ui#5]
![屏幕截图(21)](https://github.com/feihua/zero-admin-ui/assets/26198054/ff282c17-d8fa-41db-b405-87319da3ba1c)

**Comment by feihua** [comment]
node的版本是多少啊

**Comment by 780662833** [comment]
v16.14.1

**Comment by 780662833** [comment]
> node的版本是多少啊

node v16.14.1
npm 8.5.0

**Comment by feihua** [comment]
依赖的问题，只能删除多下几次看下

**Comment by 780662833** [comment]
> 依赖的问题，只能删除多下几次看下

试了不行

**Comment by feihua** [comment]
删除 ./src/components/index.md试下

**Comment by 780662833** [comment]
> 删除 ./src/components/index.md试下

谢谢可以了
